### ISSUE TITLE
cant get libspotify application key

### ISSUE THREAD

**Issue by KJThaDon** [akezeke/spotyxbmc2#15]
I don't know if i am doing something wrong but I cannot get an application key from https://developer.spotify.com/en/libspotify/application-key/. I am using the correct login information and i have a premium account. Is there something I am missing?

Thanks

**Comment by flofis** [comment]
I am having the same problem and I am fairly certain that this is either related to using facebook to login or being from a specific country. In my case, logging in on the spotify page usually redirects to /login/at.... wheres the login on the developer page plainly redirects to /login/en/ which does not work for me at all.

**Comment by betz** [comment]
Had the same problem. 
Is indeed because you have a facebook spotify account.

On following link you can create a password: https://www.spotify.com/se/help/faq/devices/connect-devices/
Use the account number you find on your profile overview page together with the password you created on proevious link afterwards.

**Comment by flofis** [comment]
Gosh, many thanks :)
